---
- name: Install BigBlueButton
  hosts: localhost
  connection: local
  gather_facts: True
  roles:
    - role: ansible-role-bigbluebutton
      bbb_server_name: bbb.edu-cattle.de
      bbb_configure_nat: True
      bbb_install_demo: True
      bbb_install_check: True
      bbb_configure_ssl: True
      bbb_ssl_email: stolle.login+nfg-bbb@icloud.com

